### PR TITLE
Csb 5887

### PR DESCRIPTION
**Pull request by johnpoth**
Hope this is ok, thanks !

### CODE REVIEW

**Comment by Croway** [comment]
Hi @johnpoth , The changes for streamingWithLargeRequestAndResponseBody are working as expected!

With your changes there are 12 failing tests same as without changes, I have streaming() test failing locally for me with your changes

**Comment by johnpoth** [comment]
Thanks @Croway ! Even with the [fix streaming](https://github.com/Croway/camel-spring-boot/pull/16/commits/c89b77c5bb994aa090a6d91c38a503a4c3a467e3) commit ? Will double check

**Comment by Croway** [comment]
Yea, even with that, but if it work for you, Ill merge

**Comment by johnpoth** [comment]
Ok let me double check then

**Comment by johnpoth** [comment]
So `mvn clean install -Dtest=SpringBootPlatformHttpCertificationTest#streaming` seems to work for me:

`[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.206 s -- in org.apache.camel.component.platform.http.springboot.SpringBootPlatformHttpCertificationTest
`

**Pull request merged**
